wip
Signed-off-by: Luan Santos <lsantos@pivotal.io>

diff --git a/bin/newextract b/bin/newextract
--- a/bin/newextract
+++ b/bin/newextract
@@ -3,6 +3,23 @@
 set -ex
 
 mkdir lang_temp
+function cleanup {
+   rm -rf lang_temp
+}
+trap cleanup EXIT
+
+if [ ! $(which goi18n) ];then
+  echo -e "\n Installing go-i18n..."
+  go get github.com/nicksnyder/go-i18n/goi18n
+fi
+
+echo -e "\n Updating i18n4go..."
+go get -u github.com/XenoPhex/i18n4go/i18n4go
+if [ $? -ne 0 ]; then
+  printf "Failed to run `go get -u github.com/XenoPhex/i18n4go/i18n4go`"
+  exit 1
+fi
+
 
 IGNORE_FILES_REGEX=".*test.go|.*resources.go|fake.*\.go|template.go"
 
@@ -28,4 +45,3 @@ if [[ $(git status --porcelain cf/i18n/resources) ]]; then
   fi
 fi
 
-rm -rf lang_temp
